#!/usr/bin/env python3
"""Derive the domain-wide-delegation scope allowlist from the inventory.

The output of this script is meant to be pasted into
Admin console -> Security -> Access and data control -> API controls ->
Domain-wide delegation -> Manage Domain Wide Delegation -> Add new.

That list is the ONLY control that survives someone editing this client, so it is
generated from the Discovery data rather than typed by hand. Two lists are produced
because they answer different questions:

  candidate  every read-only scope that any in-scope read method accepts
  cover      a greedy minimal set covering the same methods

`cover` is minimal by COUNT, not by PRIVILEGE - greedy prefers the scope that covers
most methods, which is the broad one. Narrowing (e.g. drive.metadata.readonly instead
of drive.readonly, where metadata is enough) is a judgement call left to a human.
"""
from __future__ import annotations

import collections
import csv
import textwrap
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Tier A/B: APIs this server is designed to reach. Tier D lives in API-SURFACE.md.
IN_SCOPE = {
    "admin", "groupssettings", "cloudidentity", "alertcenter", "vault",
    "drive", "driveactivity", "gmail", "calendar", "licensing",
    "chromemanagement", "chromepolicy", "meet", "script",
}

# Deliberately NOT on the phase-1 allowlist. Each entry is a decision with a reason,
# not a gap - the scopes are still emitted, commented out, so re-adding one is a
# visible edit rather than a rediscovery.
DEFERRED = {
    "gmail": (
        "The narrowest read-only scope reaching settings.filters.list is gmail.readonly, "
        "which also reads every message body in every mailbox (API-SURFACE.md #10). Mail "
        "flow does not need it - reports.activities.list(applicationName=gmail) is covered "
        "by admin.reports.audit.readonly. Deferred 2026-09-01 so the key file cannot read "
        "mail. Re-adding buys the filter/forwarding/delegate persistence audit and nothing else."
    ),
}


def main() -> int:
    allrows = list(csv.DictReader((ROOT / "analysis" / "operation-inventory.csv").open()))
    rows = [r for r in allrows if r["api"] in IN_SCOPE and r["api"] not in DEFERRED]
    reads = [r for r in rows if r["class"].startswith("READ")]
    deferred_reads = [
        r for r in allrows if r["api"] in DEFERRED and r["class"].startswith("READ")
    ]

    candidate = sorted({s for r in reads for s in r["readonly_scopes"].split() if s})

    # Greedy set cover over the methods that a read-only scope can actually reach.
    coverable = {r["method_id"]: set(r["readonly_scopes"].split()) for r in reads if r["readonly_scopes"]}
    uncovered, cover = set(coverable), []
    while uncovered:
        best = max(candidate, key=lambda s: sum(s in coverable[m] for m in uncovered))
        hits = {m for m in uncovered if best in coverable[m]}
        if not hits:
            break
        cover.append((best, len(hits)))
        uncovered -= hits

    trapped = collections.defaultdict(list)
    for r in reads:
        if r["class"] == "READ_NEEDS_RW":
            for s in r["scopes"].split():
                trapped[s].append(r["method_id"])

    out = ROOT / "analysis" / "dwd-scope-allowlist.txt"
    with out.open("w") as fh:
        fh.write("# Domain-wide delegation scope allowlist - GENERATED by scripts/scope_allowlist.py\n")
        fh.write("# Do not edit by hand. Paste the comma-joined list into the Admin console.\n\n")
        fh.write(f"# --- MINIMAL COVER ({len(cover)} scopes, reaches every read-only-reachable method) ---\n")
        for s, n in cover:
            fh.write(f"{s}    # covers {n} methods\n")
        fh.write(f"\n# --- FULL CANDIDATE SET ({len(candidate)} scopes) ---\n")
        for s in candidate:
            fh.write(f"# {s}\n")
        fh.write("\n# --- NOT READ-ONLY: these reads require a WRITE-CAPABLE scope ---\n")
        fh.write("# Adding any line below puts write capability on the allowlist. Decide per line.\n")
        for s in sorted(trapped):
            fh.write(f"# {s}\n")
            for m in sorted(trapped[s]):
                fh.write(f"#     reaches: {m}\n")
        fh.write("\n# --- DEFERRED: in scope for the repo, off the phase-1 allowlist ---\n")
        for api, why in sorted(DEFERRED.items()):
            n = len([r for r in deferred_reads if r["api"] == api])
            fh.write(f"#\n# {api}  ({n} read methods forgone)\n")
            for line in textwrap.wrap(why, 86):
                fh.write(f"#   {line}\n")
            for sc in sorted({s for r in deferred_reads if r["api"] == api
                              for s in r["readonly_scopes"].split()}):
                fh.write(f"#   OFF: {sc}\n")

        fh.write("\n# --- COMMA-JOINED (minimal cover only) ---\n")
        fh.write("# " + ",".join(s for s, _ in cover) + "\n")

    print(f"in-scope methods: {len(rows)}   reads: {len(reads)}")
    print(f"candidate read-only scopes: {len(candidate)}   minimal cover: {len(cover)}\n")
    print("MINIMAL COVER")
    for s, n in cover:
        print(f"  {s:70} {n:>4} methods")
    print(f"\nWRITE-CAPABLE scopes required by {sum(len(v) for v in trapped.values())} reads:")
    for s in sorted(trapped):
        print(f"  {s:70} {len(trapped[s]):>4} reads")
    if uncovered:
        print(f"\nUNREACHABLE read-only ({len(uncovered)}): {sorted(uncovered)[:5]} ...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
